dfBares <- read.csv(file="BaresPoc.csv", header = T)
dfACV <-read.csv(file = "ACVPoc.csv",header = T)
dfBares$count<- rep(1,nrow(dfBares))
dfACV$count<- rep(1,nrow(dfACV))
library(reshape2)
#dfSumBares<-dcast(dfBares,Localidad+Nombre.de.asentamiento.humano+zona~count, sum)
dfSumBares<-dcast(dfBares,Localidad+zona~count, sum)
dfSumACV <-dcast(dfACV,Zona~count,sum)
source("PoCFunctions.R")
dfZona <- createGrid(19.266608,-99.266069,19.569618,-98.933722,10)
write.csv(dfZona,file="dfSumZona.csv")
write.csv(dfSumACV,file="dfSumACV.csv")
write.csv(dfSumBares,file="dfSumBares.csv")